# Generated by Django 3.1.7 on 2021-03-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('category', models.CharField(choices=[('other', 'Другое'), ('laptops', 'Ноутбуки'), ('tablets', 'Планшеты'), ('accessories', 'аксессуары')], default='other', max_length=100)),
                ('remainder', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товар',
                'db_table': 'products',
            },
        ),
    ]
