# Generated by Django 3.1.7 on 2021-04-08 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
